### ISSUE TITLE
Building UnEgg on Mac OS X 10.7.5

### ISSUE THREAD

**Issue by RobK88** [dterracino/UnEgg#1]
I have been trying to get UnEgg to compile on Mac OS X 10.7.5.  I tried using gcc12 and clang-14.  Both complain of errors in the code.

e.g `/Users/rob/Downloads/unegg.tar/unegg_con/../lib/col/src/stringt/../col_type_traits/col_type_traits.h:128:45: error: unknown class name 'true_type'; did you mean 'std::true_type'?`

Your license file states that UnEgg was successfully compiled on Mac OS X 10.6.  Can you provide me with the steps you used to compile UnEgg on Mac OS X.  Thanks!
